# Generated by Django 5.2.7 on 2025-11-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('nombre_tela', models.CharField(max_length=200, verbose_name='Nombre de Tela (Artículo)')),
                ('tipo', models.CharField(choices=[('Tela', 'Tela'), ('Toalla', 'Toalla'), ('Paquete', 'Paquete'), ('Bulto', 'Bulto'), ('Otro', 'Otro')], default='Tela', max_length=50)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('composicion', models.CharField(blank=True, max_length=200, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Largo (m)')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancho (m)')),
                ('peso_por_pieza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso por Pieza (kg)')),
                ('peso_aprox', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Aproximado (kg)')),
                ('paquete_pz', models.IntegerField(blank=True, null=True, verbose_name='Piezas por Paquete (PAQUETE)')),
                ('paquetes_bulto', models.IntegerField(blank=True, null=True, verbose_name='Paquetes por Bulto')),
                ('bulto_pz', models.IntegerField(blank=True, null=True, verbose_name='Piezas por Bulto (BULTO)')),
                ('pz', models.IntegerField(default=0, verbose_name='Piezas (Stock Actual)')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Notas')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientoinventario_set', to='app.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
