# Generated by Django 5.2.7 on 2025-10-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Blanco', 'Blanco'), ('Negro', 'Negro')], default='Blanco', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.CharField(choices=[('Metros', 'Metros'), ('Unidades', 'Unidades'), ('Kilos', 'Kilos')], default='Medidas', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_tela',
            field=models.CharField(choices=[('Algodon', 'Algodón'), ('Poliéster', 'Poliéster'), ('Seda', 'Seda'), ('Lino', 'Lino')], default='Nombre Tela', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='piezas',
            field=models.IntegerField(default=0, verbose_name='Piezas (Stock)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Tela', 'Tela'), ('Hilo', 'Hilo'), ('Boton', 'Botón'), ('Cierre', 'Cierre')], default='Tipo', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='Descripción (Comentarios)', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='SKU (Código de Barras)', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
    ]
