# Generated by Django 5.2.7 on 2025-10-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_producto_nombre_remove_producto_stock_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='composicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_tela',
            field=models.CharField(choices=[('Algodon', 'Algodón'), ('Poliéster', 'Poliéster')], default='Nombre Tela', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('P9', 'P9'), ('P7', 'P7'), ('P3', 'P3'), ('P2', 'P2'), ('P5', 'P5'), ('P12', 'P12'), ('Opal', 'Opal'), ('Manta', 'Manta'), ('Granite', 'Granite'), ('Etamina', 'Etamina'), ('Marquisett', 'Marquisett')], default='Tipo', max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
