# Generated by Django 5.2.7 on 2025-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_composicion_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='medidas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='piezas',
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancho (Anch)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largo (L)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_aprox',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Aproximado (kg)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_por_pz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso por Pieza (gr)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pz',
            field=models.IntegerField(default=0, verbose_name='Piezas (Pz)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción / Comentarios'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_tela',
            field=models.CharField(max_length=100, verbose_name='Nombre Tela / Artículo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Rollo', 'Rollo'), ('Paquete', 'Paquete'), ('Bulto', 'Bulto'), ('Toalla', 'Toalla')], default='Rollo', max_length=50),
        ),
    ]
